### ISSUE TITLE
fcitx5-virtualkeyboard-ui base:fcitx5.5.0.8：Characters cannot be used, numbers can be used

### ISSUE THREAD

**Issue by zcj-git520** [clear-code/fcitx5-virtualkeyboard-ui#2]
hello

Soft keyboard: characters can not be used, numbers and other characters can be used, why

Hope to reply!

**Comment by daipom** [comment]
@zcj-git520 Could you share a screenshot?

**Comment by zcj-git520** [comment]
ok!
None of the red boxes can be used except the two arrows. I will see if there is a problem with the source code (NormalKey::click)


Looking forward to your reply!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "clear-code/fcitx5-virtualkeyboard-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [clear-code/fcitx5-virtualkeyboard-ui] fcitx5-virtualkeyboard-ui base:fcitx5.5.0.8：Characters cannot be used, numbers can be used (Issue #2)





 
@zcj-git520 Could you share a screenshot?

**Comment by daipom** [comment]
Sorry, I can't see the picture. Could you share it again?
I think you may have failed to post the picture.

**Comment by zcj-git520** [comment]
None of the red boxes can be used except the two arrows. I will see if there is a problem with the source code (NormalKey::click)

Looking forward to your reply!

**Comment by zcj-git520** [comment]
![keyboard](https://user-images.githubusercontent.com/71475834/165227513-9873970e-14c4-4b0d-bc58-4443c6271a04.png)
ok!
None of the red boxes can be used except the two arrows. I will see if there is a problem with the source code (NormalKey::click)
Looking forward to your reply!


> 抱歉，我看不到图片。你能再分享一次吗？我想你可能没有发布这张照片。

**Comment by ashie** [comment]
What your application?
The application need to support text-input-v1 protocol of Wayland.
In addition, you need additional patches for fcitx5 core: https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites

**Comment by zcj-git520** [comment]
> https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites

Yeah, the app is From Weston,

I put fcitx and fcitx-utils and fcitx-Wayland in fcitx5-virtulboard-UI Replace with SRC /lib/fcitx and fcitx-utils in https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites And FCITX-Wayland, I don't know if that's going to matter.

**Comment by zcj-git520** [comment]
> 您的应用是什么？应用程序需要支持 Wayland 的文本输入 v1 协议。此外，您还需要 fcitx5 内核的其他修补程序：https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites

Now characters like numbers and special characters can be typed, except characters that cannot be typed

**Comment by daipom** [comment]
Can the following keys be typed?

* `,`
* `.`
* `!`
* `?`

And the following keys can not be typed?

* `a`, `b`, ...
* `space`, `Enter`, `Back`, ...

**Comment by daipom** [comment]
Somehow `WaylandIMInputContextV1` may not be selected in your environment.

https://github.com/clear-code/fcitx5-virtualkeyboard-ui/blob/master/src/virtualkeygeneral.cpp#L27

The `inputContext` here should be `WaylandIMInputContextV1`.

If it is not `WaylandIMInputContextV1`, such behavior can occur.

**Comment by zcj-git520** [comment]
> Can the following keys be typed?
> 
> * `,`
> * `.`
> * `!`
> * `?`
> 
> And the following keys can not be typed?
> 
> * `a`, `b`, ...
> * `space`, `Enter`, `Back`, ...

These can be used，Including digital
> * `,`
> * `.`
> * `!`
> * `?`

These are not allowed：
> * `a`, `b`, ...
> * `space`, `Enter`, `Back`, ...

**Comment by zcj-git520** [comment]
> WaylandIMInputContextV1

Yes, when I look at the code, it seems to be the same problem, because the buttons that go to the NormalKey::click interface are not available. So, what do I do to make the character usable

**Comment by daipom** [comment]
> > https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites
> 
> Yeah, the app is From Weston,
> 
> I put fcitx and fcitx-utils and fcitx-Wayland in fcitx5-virtulboard-UI Replace with SRC /lib/fcitx and fcitx-utils in https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites And FCITX-Wayland, I don't know if that's going to matter.

Did you include patches of `src/frontend` in https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites?

You need the following patches of `WaylandIMInputContextV1`.

* https://github.com/clear-code/fcitx5/commit/d5fec9155b040c1eb8e51dfe9fbfbd8bfec9c25c

**Comment by zcj-git520** [comment]
> > > https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites
> > 
> > 
> > Yeah, the app is From Weston,
> > I put fcitx and fcitx-utils and fcitx-Wayland in fcitx5-virtulboard-UI Replace with SRC /lib/fcitx and fcitx-utils in https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites And FCITX-Wayland, I don't know if that's going to matter.
> 
> Did you include patches of `src/frontend` in https://github.com/clear-code/fcitx5/tree/5.0.8+virtual-keyboard-prerequisites?
> 
> You need the following patches of `WaylandIMInputContextV1`.
> 
> * [clear-code/fcitx5@d5fec91](https://github.com/clear-code/fcitx5/commit/d5fec9155b040c1eb8e51dfe9fbfbd8bfec9c25c)

Thank you very much, you can use it, thank you, I have another question, how to switch the input method of soft keyboard, thank you

**Comment by daipom** [comment]
> how to switch the input method of soft keyboard,

You have to install input-method-engines to Fcitx5.

* Available language and add-on: https://github.com/clear-code/fcitx5-virtualkeyboard-ui#whats-this
* About input-method-engine: https://fcitx-im.org/wiki/Input_method_engines

For example, if you need Simplified-Chinese, you have to install [fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons)

After installing it, you have to add the configuration `~/.config/fcitx5/profile`.
You can edit the config file directly, or use GUI tool: https://fcitx-im.org/wiki/Configtool_(Fcitx_5)

* Configuration example: https://github.com/clear-code/fcitx5-virtualkeyboard-ui#example-configuration

Then you can change the keyboard by pushing the language button (`US`).

Here is an example using us-keyboard and pinyin (fcitx5-chinese-addons).

* Set group-0 to us-keyboard and group-1 to pinyin-keyboard.

```
[Groups/0]
# Group Name
Name=US
# Layout
Default Layout=us
# Default Input Method
DefaultIM=keyboard-us

[Groups/0/Items/0]
# Name
Name=keyboard-us
# Layout
Layout=

[Groups/1]
# Group Name
Name=CH
# Layout
Default Layout=us
# Default Input Method
DefaultIM=pinyin

[Groups/1/Items/0]
# Name
Name=keyboard-us
# Layout
Layout=

[Groups/1/Items/1]
# Name
Name=pinyin
# Layout
Layout=

[GroupOrder]
0=US
1=CH
```

**Comment by zcj-git520** [comment]
> [Groups/0]

Yes, input engine was added, modified in.config/fcitx5/profile (as you did), but profile was overwritten after I restarted the system.

Profile file: [Groups/0]
+


Name=CH


Default Layout=us


DefaultIM=pinyin



[Groups/0/Items/0]


Name=keyboard-us


Layout=



[Groups/0/Items/1]


Name=pinyin


Layout=



[GroupOrder]

0=CH

But I was able to type English and Chinese using the physical keyboard (CTRL + space). The current problem is that the files are overwritten after the system restarts!

**Comment by ashie** [comment]
Please kill weston & fcitx5 before modifying ~/.config/fcitx5/profile.
Since GUI is gone, you'll need to modify it via ssh or serial console, or mount your disk image on other Linux system.

**Comment by zcj-git520** [comment]
> Please kill weston & fcitx5 before modifying ~/.config/fcitx5/profile. Since GUI is gone, you'll need to modify it via ssh or serial console, or mount your disk image on other Linux system.

Yes, I set profile, I found that the soft keyboard is inconsistent with the input method, for example: CH is displayed on the software disk, but the input is English unless you use the physical keyboard to switch, I see Fcitx5 /profile, the input method is Pinying, the CH key can not be used, I don't know why

**Comment by daipom** [comment]
@zcj-git520
Something seems to be wrong.
The software keyboard is designed to synchronize with the current input method.

> CH is displayed on the software disk, but the input is English unless you use the physical keyboard to switch

I would like to know more about this condition.
Does this mean that CH is shown on the language button but Chinese cannot be entered?
And if you use the physical key to switch the input method, then you can use the Chinese software keyboard?

**Comment by zcj-git520** [comment]
> @zcj-git520 Something seems to be wrong. The software keyboard is designed to synchronize with the current input method.
> 
> > CH is displayed on the software disk, but the input is English unless you use the physical keyboard to switch
> 
> I would like to know more about this condition. Does this mean that CH is shown on the language button but Chinese cannot be entered? And if you use the physical key to switch the input method, then you can use the Chinese software keyboard?

Yes, the soft keyboard shows CH, which is in English, unless you use the physical keyboard "CTRL + space" to switch the input method, which is in Chinese

**Comment by daipom** [comment]
@zcj-git520 
Oh, I am sorry. I found the bug.
The first group must be US for now. This is a bug.

The config of https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1109776314 works well.

However, the config of https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1110631232 doesn't work well because the first group is not US.

I will fix this. Sorry for the inconvenience.

**Comment by daipom** [comment]
@zcj-git520 
I found a workaround.
By setting just one item without keyboard-us, you can use pinyin by default.
However, Ficix5 says the first item should be a simple keyboard layout such as keyboard-us, so this may be not a good setting.

```
[Groups/0]
# Group Name
Name=CH
# Layout
Default Layout=us
# Default Input Method
DefaultIM=pinyin

[Groups/0/Items/0]
# Name
Name=pinyin
# Layout
Layout=

[GroupOrder]
0=CH
```

**Comment by zcj-git520** [comment]
> @zcj-git520 I found a workaround. By setting just one item without keyboard-us, you can use pinyin by default. However, Ficix5 says the first item should be a simple keyboard layout such as keyboard-us, so this may be not a good setting.
> 
> ```
> [Groups/0]
> # Group Name
> Name=CH
> # Layout
> Default Layout=us
> # Default Input Method
> DefaultIM=pinyin
> 
> [Groups/0/Items/0]
> # Name
> Name=pinyin
> # Layout
> Layout=
> 
> [GroupOrder]
> 0=CH
> ```

It seems impossible

/config/fcirtx5/profile defaults to this configuration when fcitx5 soft keyboard is enabled:

[Groups/0]



Name=CH



Default Layout=us



DefaultIM=pinyin



[Groups/0/Items/0]


Name=pinyin


Layout=



[GroupOrder]

0=CH

However, the soft keyboard displays CH, but the input is still in English, which is the same as setting a profile https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1111704024

**Comment by daipom** [comment]
Hmmm, that's strange, it works fine with that config in my environment...

Did you restart Fcitx5 and weston after you modified the config?

**Comment by zcj-git520** [comment]
> Hmmm, that's strange, it works fine with that config in my environment...
> 
> Did you restart Fcitx5 and weston after you modified the config?

I misread the configuration:

Name=keyboard-us by default,

I didn't try your one. Can you only use Chinese for this one? Can you still use English? Can I switch the input method?
![image](https://user-images.githubusercontent.com/71475834/166219118-156224bf-3973-4230-864f-f18d2df40bbf.png)

**Comment by daipom** [comment]
You can use only Chinese keyboard with the config of https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114677533.
Although you can't use US keyboard with the config, you can input alphabets by the `确认` button.

If you need to use both of US keyboard and Chinese keyboard, then you need to use the config of https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1109776314.
You need to set 2 groups: `Groups/0` for US and `Groups/1` for pinyin.

Because of the bug I mentioned in https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114672391, we can't set pinyin to `Groups/0` now.

**Comment by daipom** [comment]
The language button switches the groups, not the items.

**Comment by zcj-git520** [comment]
> You can use only Chinese keyboard with the config of [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114677533). Although you can't use US keyboard with the config, you can input alphabets by the button.`确认`
> 
> If you need to use both of US keyboard and Chinese keyboard, then you need to use the config of [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1109776314). You need to set 2 groups: for US and for pinyin.`Groups/0``Groups/1`
> 
> Because of the bug I mentioned in [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114672391), we can't set pinyin to now.`Groups/0`

Is this the configuration of the Chinese and English keyboard you said:

'''

[Groups/0]

# Group Name

Name=US

# Layout

Default Layout=us

# Default Input Method

DefaultIM=keyboard-us



[Groups/0/Items/0]

# Name

Name=keyboard-us

# Layout

Layout=



[Groups/1]

# Group Name

Name=CH

# Layout

Default Layout=us

# Default Input Method

DefaultIM=pinyin



[Groups/1/Items/0]

# Name

Name=keyboard-us

# Layout

Layout=



[Groups/1/Items/1]

# Name

Name=pinyin

# Layout

Layout=



[GroupOrder]

0=US

1=CH

'''

**Comment by zcj-git520** [comment]
Ok, I will try it. Did you give me the configuration of the soft keyboard in Chinese and English that you said?

> > how to switch the input method of soft keyboard,
> 
> You have to install input-method-engines to Fcitx5.
> 
> * Available language and add-on: https://github.com/clear-code/fcitx5-virtualkeyboard-ui#whats-this
> * About input-method-engine: https://fcitx-im.org/wiki/Input_method_engines
> 
> For example, if you need Simplified-Chinese, you have to install [fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons)
> 
> After installing it, you have to add the configuration . You can edit the config file directly, or use GUI tool: https://fcitx-im.org/wiki/Configtool_(Fcitx_5)`~/.config/fcitx5/profile`
> 
> * Configuration example: https://github.com/clear-code/fcitx5-virtualkeyboard-ui#example-configuration
> 
> Then you can change the keyboard by pushing the language button ().`US`
> 
> Here is an example using us-keyboard and pinyin (fcitx5-chinese-addons).
> 
> * Set group-0 to us-keyboard and group-1 to pinyin-keyboard.
> 
> ```
> [Groups/0]
> # Group Name
> Name=US
> # Layout
> Default Layout=us
> # Default Input Method
> DefaultIM=keyboard-us
> 
> [Groups/0/Items/0]
> # Name
> Name=keyboard-us
> # Layout
> Layout=
> 
> [Groups/1]
> # Group Name
> Name=CH
> # Layout
> Default Layout=us
> # Default Input Method
> DefaultIM=pinyin
> 
> [Groups/1/Items/0]
> # Name
> Name=keyboard-us
> # Layout
> Layout=
> 
> [Groups/1/Items/1]
> # Name
> Name=pinyin
> # Layout
> Layout=
> 
> [GroupOrder]
> 0=US
> 1=CH
> ```



> You can use only Chinese keyboard with the config of [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114677533). Although you can't use US keyboard with the config, you can input alphabets by the button.`确认`
> 
> If you need to use both of US keyboard and Chinese keyboard, then you need to use the config of [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1109776314). You need to set 2 groups: for US and for pinyin.`Groups/0``Groups/1`
> 
> Because of the bug I mentioned in [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114672391), we can't set pinyin to now.`Groups/0`
Ok, I will try it. Did you give me the configuration of the soft keyboard in Chinese and English that you said?https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1109776314
 I used this and it didn't seem to work

**Comment by zcj-git520** [comment]
> You can use only Chinese keyboard with the config of [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114677533). Although you can't use US keyboard with the config, you can input alphabets by the button.`确认`
> 
> If you need to use both of US keyboard and Chinese keyboard, then you need to use the config of [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1109776314). You need to set 2 groups: for US and for pinyin.`Groups/0``Groups/1`
> 
> Because of the bug I mentioned in [#2 (comment)](https://github.com/clear-code/fcitx5-virtualkeyboard-


ui/issues/2#issuecomment-1114672391), we can't set pinyin to now.`Groups/0`
Ok, I will try it. Did you give me the configuration of the soft keyboard in Chinese and English that you said? https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1109776314I used this and it didn't seem to work

**Comment by daipom** [comment]
> Did you give me the configuration of the soft keyboard in Chinese and English that you said?
> it didn't seem to work

Do you mean this config does not work?

```
[Groups/0]
# Group Name
Name=US
# Layout
Default Layout=us
# Default Input Method
DefaultIM=keyboard-us

[Groups/0/Items/0]
# Name
Name=keyboard-us
# Layout
Layout=

[Groups/1]
# Group Name
Name=CH
# Layout
Default Layout=us
# Default Input Method
DefaultIM=pinyin

[Groups/1/Items/0]
# Name
Name=keyboard-us
# Layout
Layout=

[Groups/1/Items/1]
# Name
Name=pinyin
# Layout
Layout=

[GroupOrder]
0=US
1=CH
```

**Comment by zcj-git520** [comment]
> > Did you give me the configuration of the soft keyboard in Chinese and English that you said?
> > it didn't seem to work
> 
> Do you mean this config does not work?
> 
> ```
> [Groups/0]
> # Group Name
> Name=US
> # Layout
> Default Layout=us
> # Default Input Method
> DefaultIM=keyboard-us
> 
> [Groups/0/Items/0]
> # Name
> Name=keyboard-us
> # Layout
> Layout=
> 
> [Groups/1]
> # Group Name
> Name=CH
> # Layout
> Default Layout=us
> # Default Input Method
> DefaultIM=pinyin
> 
> [Groups/1/Items/0]
> # Name
> Name=keyboard-us
> # Layout
> Layout=
> 
> [Groups/1/Items/1]
> # Name
> Name=pinyin
> # Layout
> Layout=
> 
> [GroupOrder]
> 0=US
> 1=CH
> ```

Yes，

**Comment by daipom** [comment]
Hmmm, this config works fine in my environment.

You will see the US keyboard first.
If you press the language button, then you will see the Chinese keyboard.

**Comment by zcj-git520** [comment]
> Hmmm, this config works fine in my environment.
> 
> You will see the US keyboard first. If you press the language button, then you will see the Chinese keyboard.

I found a new problem, https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114677533 this can be used, but the special characters are not allowed.
![image](https://user-images.githubusercontent.com/71475834/166894851-68a615fc-4d90-4bf7-bd26-55efbdc62f0c.png)

English keyboard configuration https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114724745 Settings. After weston is restarted, the configuration file changes:
![image](https://user-images.githubusercontent.com/71475834/166894220-e3ff38ae-f061-45a0-ae90-ae714b6a3a52.png)

**Comment by zcj-git520** [comment]
> Hmmm, this config works fine in my environment.
> 
> You will see the US keyboard first. If you press the language button, then you will see the Chinese keyboard.

A new problem is that when switching from English keyboard to Chinese keyboard (US -> CH), there is a flash back (soft keyboard disappears), and it is very easy to appear. Ch -> US ok, somehow.

**Comment by daipom** [comment]
@zcj-git520

The problem of https://github.com/clear-code/fcitx5-virtualkeyboard-ui/issues/2#issuecomment-1114672391 is fixed at https://github.com/clear-code/fcitx5-virtualkeyboard-ui/pull/6 !
