### ISSUE TITLE
How to view logs

### ISSUE THREAD

**Issue by zcj-git520** [clear-code/fcitx5-virtualkeyboard-ui#3]
How to view logs

**Comment by daipom** [comment]
The virtual keyboard also outputs logs to the same log output by Fcitx5.
We can check Fcitx5 logs.

**Comment by zcj-git520** [comment]
> The virtual keyboard also outputs logs to the same log output by Fcitx5. We can check Fcitx5 logs.

Thanks for your reply;

How to view fCITx5 logs, do you need to configure, output to weston.log?

The configuration looks like this:
export DISPLAY=:0
export LD_LIBRARY_PATH="/usr/lib:$LD_LIBRARY_PATH"
/usr/bin/fcitx5 --verbose "*=5"

**Comment by daipom** [comment]
In my environment, I can view Fcitx5 logs in Weston's logs without any settings regarding logs.

**Comment by zcj-git520** [comment]
> In my environment, I can view Fcitx5 logs in Weston's logs without any settings regarding logs.

ok
