### ISSUE TITLE
The soft keyboard flashes back

### ISSUE THREAD

**Issue by zcj-git520** [clear-code/fcitx5-virtualkeyboard-ui#4]
hello：
     I have a problem: when switching from English keyboard to Chinese keyboard (US -> CH), there is a flash back (soft keyboard disappears), and it is very easy to appear. Ch -> US ok, somehow
hank you，Looking forward to your reply！

**Comment by daipom** [comment]
Sorry for the late response.

We have confirmed that the first loading of the pinyin keyboard is slow.
The loading of the pinyin keyboard seems to be a heavy process.

However, the switch should be smooth from the second time.

> there is a flash back (soft keyboard disappears)

Does that mean that Fcitx5 terminated abnormally?

**Comment by zcj-git520** [comment]
> Sorry for the late response.
> 
> We have confirmed that the first loading of the pinyin keyboard is slow. The loading of the pinyin keyboard seems to be a heavy process.
> 
> However, the switch should be smooth from the second time.
> 
> > there is a flash back (soft keyboard disappears)
> 
> Does that mean that Fcitx5 terminated abnormally?

Thanks for your reply;

1, FCITX5 does not stop working, when click the switch button, the software disk disappears, click the input box, the software disk up, is the English keyboard

2. When the soft keyboard can be switched to Chinese, it can be switched continuously, but I do not know how many times after switching, the keyboard will disappear when switching occurs; When you click the input box, the US keyboard will be activated, and when you switch the Chinese keyboard, it will disappear; It's the same when you're trying

**Comment by daipom** [comment]
It looks like Fcitx5 terminated abnormally and restarted.

The following settings may improve the language switching process.

`~/.config/fcitx5/config`

```
ShowInputMethodInformation=False
```

Could you please try it?

**Comment by zcj-git520** [comment]
> It looks like Fcitx5 terminated abnormally and restarted.
> 
> The following settings may improve the language switching process.
> 
> `~/.config/fcitx5/config`
> 
> ```
> ShowInputMethodInformation=False
> ```
> 
> Could you please try it?

Thank you. I'll try

**Comment by daipom** [comment]
Sorry, that setting is in `[Behavior]`.

```
[Behavior]
ShowInputMethodInformation=False
```

**Comment by zcj-git520** [comment]
> Sorry, that setting is in `[Behavior]`.
> 
> ```
> [Behavior]
> ShowInputMethodInformation=False
> ```

I just thought there was a problem with the feedback. I'm giving it a try

**Comment by zcj-git520** [comment]
> > Sorry, that setting is in `[Behavior]`.
> > ```
> > [Behavior]
> > ShowInputMethodInformation=False
> > ```
> 
> I just thought there was a problem with the feedback. I'm giving it a try



> Sorry, that setting is in `[Behavior]`.
> 
> ```
> [Behavior]
> ShowInputMethodInformation=False
> ```
I test found that there is still the problem of "flash back" before, but "flash back" is not as high as before; My configuration is as follows.
![image](https://user-images.githubusercontent.com/71475834/167590829-db9f0bfe-9f82-4a1a-8eef-d5d970eeb439.png)

**Comment by daipom** [comment]
Are you editing `~/.config/fcitx5/profile`?

That setting must be written to `~/.config/fcitx5/config`.

They are different files.

**Comment by zcj-git520** [comment]
> Are you editing `~/.config/fcitx5/profile`?
> 
> That setting must be written to `~/.config/fcitx5/config`.
> 
> They are different files.

Ha ha ha, misread, down to the test feeling is ok, flash back is very low, but flash back is there
